### ISSUE TITLE
[FEATURE] Provide an EAP channel

### ISSUE THREAD

**Issue by juherr** [Nasller/CodeGlancePro#120]
With the latest IDEA EAP (2024.1), the plugin is broken:
```
com.intellij.diagnostic.PluginException: 'boolean it.unimi.dsi.fastutil.objects.ObjectArrayList.addAll(it.unimi.dsi.fastutil.objects.ObjectList)' [Plugin: com.nasller.CodeGlancePro]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:971)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:353)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.doCreateEditor(EditorFactoryImpl.java:229)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createMainEditor(EditorFactoryImpl.java:213)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createEditorBuilder$2$1.build(PsiAwareTextEditorProvider.kt:123)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.createComposite(FileEditorManagerImpl.kt:1205)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$openFileInEdt$2$1.invokeSuspend(FileEditorManagerImpl.kt:2164)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:204)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:834)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1156)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:123)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:834)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoSuchMethodError: 'boolean it.unimi.dsi.fastutil.objects.ObjectArrayList.addAll(it.unimi.dsi.fastutil.objects.ObjectList)'
	at com.nasller.codeglance.render.FastMainMinimap.<init>(FastMainMinimap.kt:53)
	at com.nasller.codeglance.render.BaseMinimap$Companion.getMinimap(BaseMinimap.kt:296)
	at com.nasller.codeglance.panel.GlancePanel.<init>(GlancePanel.kt:53)
	at com.nasller.codeglance.EditorPanelInjectorKt.setMyPanel(EditorPanelInjector.kt:127)
	at com.nasller.codeglance.EditorPanelInjectorKt.firstRunEditor(EditorPanelInjector.kt:81)
	at com.nasller.codeglance.EditorPanelInjectorKt.access$firstRunEditor(EditorPanelInjector.kt:1)
	at com.nasller.codeglance.EditorPanelInjector.editorCreated(EditorPanelInjector.kt:37)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$doCreateEditor$4(EditorFactoryImpl.java:229)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:59)
	... 50 more
```

The fix is already provided in the preview version as you aswered here: https://plugins.jetbrains.com/plugin/18824-codeglance-pro/reviews#review=96048-96051

Like some other plugins, I'd like to add the EAP channel in order to receive the compatible version via IDEA.
The related marketplace documentation is here https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html#configure-a-custom-channel

`https://plugins.jetbrains.com/plugins/preview/18824` is not working because the plugin is not found.
`https://plugins.jetbrains.com/plugins/preview/list` doesn't provide the new version
<img width="428" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/254697/af2beeb5-9b5c-4599-9eb4-bdc5aa4fbbb0">

**Comment by Nasller** [comment]
Thank you for your help. I have already published the plugin to EAP channel.

**Comment by juherr** [comment]
I confirm it is working well with the eap channel.

The URL to use is: `https://plugins.jetbrains.com/plugins/eap/18824`

**Comment by joshuataylor** [comment]
This is awesome, thanks so much. A plugin I can't live without, after coming from Sublime years ago. Thanks so much for maintaining it as well.

So JetBrains is starting to split their IDEs out more and more, which is a bit of a PITA as they use different release schedules, so different versions..

[DataSpell](DataSpell is the editor they're starting to push users of PyCharm to who want to work on dbt, and it gets a bit neglected. It's just PyCharm without the pro version of the Python debugger. :facepalm:

Anwyay, the snapshot version can't be used with it, as it's slightly older - is this locally or in a branch or something?

Error:
```
Plugin 'CodeGlance Pro' (version '1.8.1-SNAPSHOT-2024-02-18T16-09') is not compatible with the current version of the IDE, because it requires build 241.11761 or newer but the current build is DS-241.10840.15
```

[IntelliJ EAP 2024.1](https://www.jetbrains.com/idea/nextversion/) `build 241.13688.18 Released: February 22, 2024`
[PyCharm](https://www.jetbrains.com/pycharm/nextversion/): `Build #PY-241.13688.16, built on February 21, 2024` (Released: February 21, 2024)
[Datagrip](https://www.jetbrains.com/datagrip/nextversion/): `Build #DB-241.11761.8, built on February 6, 2024` (Released: February 8, 2024)
[DataSpell](https://www.jetbrains.com/dataspell/nextversion/): `Build #DS-241.10840.15, built on January 30, 2024`

**Comment by Nasller** [comment]
> This is awesome, thanks so much. A plugin I can't live without, after coming from Sublime years ago. Thanks so much for maintaining it as well.
> 
> 
> 
> So JetBrains is starting to split their IDEs out more and more, which is a bit of a PITA as they use different release schedules, so different versions..
> 
> 
> 
> [DataSpell](DataSpell is the editor they're starting to push users of PyCharm to who want to work on dbt, and it gets a bit neglected. It's just PyCharm without the pro version of the Python debugger. :facepalm:
> 
> 
> 
> Anwyay, the snapshot version can't be used with it, as it's slightly older - is this locally or in a branch or something?
> 
> 
> 
> Error:
> 
> ```
> 
> Plugin 'CodeGlance Pro' (version '1.8.1-SNAPSHOT-2024-02-18T16-09') is not compatible with the current version of the IDE, because it requires build 241.11761 or newer but the current build is DS-241.10840.15
> 
> ```
> 
> 
> 
> [IntelliJ EAP 2024.1](https://www.jetbrains.com/idea/nextversion/) `build 241.13688.18 Released: February 22, 2024`
> 
> [PyCharm](https://www.jetbrains.com/pycharm/nextversion/): `Build #PY-241.13688.16, built on February 21, 2024` (Released: February 21, 2024)
> 
> [Datagrip](https://www.jetbrains.com/datagrip/nextversion/): `Build #DB-241.11761.8, built on February 6, 2024` (Released: February 8, 2024)
> 
> [DataSpell](https://www.jetbrains.com/dataspell/nextversion/): `Build #DS-241.10840.15, built on January 30, 2024`

@joshuataylor lower version number will be provided later to adapt to it.

**Comment by joshuataylor** [comment]
I wouldn't worry too much, they'll hopefully release a version soon. Super annoying UX issue where it tells you it didn't work when adding the repository, and to check the logs... nothing there..

(Not your issue, just an annoyance with confusing UX)

![SCR-20240223-evrd](https://github.com/Nasller/CodeGlancePro/assets/225131/780305f8-6962-4e88-af63-a7b5b5ddfdbc)
