### ISSUE TITLE
[BUG] IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Javaru** [Nasller/CodeGlancePro#125]
1. Which Glance version and IDEA version?
CodeGlance Pro v1.8.1
IntelliJ IDEA Ultimate v2023.3.4 (IU-233.14475.28)

2. Can you show the complete config page picture and minimap picture?
Unfortunately I did not immediately notice this exception's occurrence, so I do not know what file I was editing at the time.

3. What is the file type used and provide text or an example of the issue that occurred?
Unfortunately I did not immediately notice this exception's occurrence, so I do not know what file I was editing at the time.

4. What steps will reproduce the issue?
Unfortunately I did not immediately notice this exception's occurrence, so I do not know what file I was editing at the time, so I cannot give repeatable steps. Sorry.

The exception happened multiple times in rapid succession (based on the timestamps in the error reporter and the index values). The stacktraces  (shown below) are identical for all occurrence, except for the index values in the message.

**Exceptions**
```
java.lang.IndexOutOfBoundsException: Index (1555) is greater than list size (1534)
java.lang.IndexOutOfBoundsException: Index (1556) is greater than list size (1534)
java.lang.IndexOutOfBoundsException: Index (1557) is greater than list size (1534)
java.lang.IndexOutOfBoundsException: Index (1561) is greater than list size (1534)
java.lang.IndexOutOfBoundsException: Index (1564) is greater than list size (1534)
```

**Representative Stacktrace:**
```
java.lang.IndexOutOfBoundsException: Index (1555) is greater than list size (1534)
	at it.unimi.dsi.fastutil.objects.AbstractObjectList.ensureIndex(AbstractObjectList.java:55)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.addAll(ObjectArrayList.java:771)
	at com.nasller.codeglance.render.FastMainMinimap.doInvalidateRange(FastMainMinimap.kt:563)
	at com.nasller.codeglance.render.FastMainMinimap.doInvalidateRange$default(FastMainMinimap.kt:557)
	at com.nasller.codeglance.render.FastMainMinimap.invalidateRange(FastMainMinimap.kt:553)
	at com.nasller.codeglance.render.FastMainMinimap.updateRangeHighlight$lambda$22(FastMainMinimap.kt:524)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by Nasller** [comment]
thanks report, i will check it later

**Comment by Nasller** [comment]
[CodeGlance Pro-1.8.2-SNAPSHOT.zip](https://github.com/Nasller/CodeGlancePro/files/14546452/CodeGlance.Pro-1.8.2-SNAPSHOT.zip)
Please use this to continue observing for a period of time
