### ISSUE TITLE
[BUG]python类型debug的时候出现错误

### ISSUE THREAD

**Issue by zzm-note** [Nasller/CodeGlancePro#144]
1. Which Glance version and IDEA version?
PyCharm：2024.2
CodeGlance pro：1.8.8

2. Can you show the complete config page picture and minimap picture?
Default configuration
3. What is the file type used and provide text or an example of the issue that occurred?
File type: .py
4. What steps will reproduce the issue?
Python debug，View the details view of the dict data type

updateMinimapData error fileType:Python

com.intellij.openapi.progress.CeProcessCanceledException: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled
	at com.intellij.openapi.progress.Cancellation.checkCancelled(Cancellation.java:39)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:158)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:329)
	at com.nasller.codeglance.render.FastMainMinimap.updateMinimapData(FastMainMinimap.kt:247)
	at com.nasller.codeglance.render.FastMainMinimap.submitUpdateMinimapDataTask(FastMainMinimap.kt:607)
	at com.nasller.codeglance.render.FastMainMinimap.doInvalidateRange(FastMainMinimap.kt:578)
	at com.nasller.codeglance.render.FastMainMinimap.doInvalidateRange$default(FastMainMinimap.kt:559)
	at com.nasller.codeglance.render.FastMainMinimap.invalidateRange(FastMainMinimap.kt:555)
	at com.nasller.codeglance.render.FastMainMinimap.updateRangeHighlight$lambda$22(FastMainMinimap.kt:526)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.nasller.codeglance.render.FastMainMinimap.updateRangeHighlight(FastMainMinimap.kt:516)
	at com.nasller.codeglance.render.FastMainMinimap.afterRemoved(FastMainMinimap.kt:513)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.fireAfterRemoved(MarkupModelImpl.java:264)
	at com.intellij.openapi.editor.impl.RangeHighlighterTree.fireAfterRemoved(RangeHighlighterTree.java:141)
	at com.intellij.openapi.editor.impl.RangeHighlighterTree.fireAfterRemoved(RangeHighlighterTree.java:9)
	at com.intellij.openapi.editor.impl.IntervalTreeImpl.removeInterval(IntervalTreeImpl.java:984)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.removeHighlighter(MarkupModelImpl.java:197)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.unregisterInTree(RangeHighlighterImpl.java:443)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.dispose(RangeMarkerImpl.java:103)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.dispose(RangeHighlighterImpl.java:448)
	at com.intellij.xdebugger.impl.ui.ExecutionPositionUi.close(ExecutionPositionUi.kt:80)
	at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseableJVM.kt:49)
	at com.intellij.xdebugger.impl.ui.ExecutionPositionUi$Companion$showUntilCancelled$3$1.invokeSuspend(ExecutionPositionUi.kt:88)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

**Comment by Nasller** [comment]
必现吗

**Comment by zzm-note** [comment]
> 必现吗

我这里必现的

**Comment by Nasller** [comment]
[CodeGlancePro-1.8.9-SNAPSHOT.zip](https://github.com/user-attachments/files/16671044/CodeGlancePro-1.8.9-SNAPSHOT.zip)

**Comment by zzm-note** [comment]
> [CodeGlancePro-1.8.9-SNAPSHOT.zip](https://github.com/user-attachments/files/16671044/CodeGlancePro-1.8.9-SNAPSHOT.zip) 试下这个看看

可以了，现在不报错了

**Comment by Nasller** [comment]
好的，感谢，继续观察一段时间

**Comment by zzm-note** [comment]
> 好的，感谢，继续观察一段时间

OK，有问题我会及时反馈
