### ISSUE TITLE
Plugin broke when trying to hide original scrollbar

### ISSUE THREAD

**Issue by ZaLiTHkA** [Nasller/CodeGlancePro#146]
> NOTE: I'm not using the "bug" template explicitly here, because I'm not sure if this is an actual bug with the plugin, or if something else has gone wrong with my installation.

running WebStorm `2024.2.0.1` with CodeGlance Pro `1.8.8`. with a project open, I went into my settings and enabled the "Hide Original ScrollBar And ErrorStripes" option and hit "Apply".. almost instantly, the document minimap sidebar disappeared and the main area of my settings window changed to a "busy" spinner, as seen below:

![image](https://github.com/user-attachments/assets/c0a25ede-bdde-48ea-90ed-fe698cce8139)

at this time, trying to select any othe settings page simply refuses to respond... until I close and reopen the settings modal, when the last page I tried to switch to (Editor, Version Contol, Plugins, etc) will then be visible. trying to navigate back to the "CodeGlance Pro" settings page puts me back in the same situation immediately.

I've tried disabling and re-enabling the plugin, I've tried removing and reinstalling it, I've tried updating settings in WebStorm on Windows to see if my settings will sync across to Linux, nothing helped.

I really don't want to reset my entire IDE settings, especially since I'm not even sure that doing so would resolve this.. but I can't seem to get this plugin working again now. please help?

**Comment by Nasller** [comment]
have any error log? can you see the error in the idea.log file?

**Comment by ZaLiTHkA** [comment]
I just checked the `idea.log` file in the archive created by the "Collect Logs and Diagnostics Data" option in WebStorm's launcher.

I don't use Java or Kotlin, so much of the logging from JetBrains IDEs doesn't really mean much to me.. could I ask you to have a look? at least you would know what to look for...

[idea.log](https://github.com/user-attachments/files/16708661/idea.log)

NOTE: this log should also include entries from when I changed the specific setting that started this whole thing.

**Comment by ZaLiTHkA** [comment]
I also just saw that `1.8.9` was released.. should I update and try again? happy to stick on `1.8.8` for the remainder of debugging this one, if that helps.

**Comment by Nasller** [comment]
you can try 1.8.9, i see the idea.log, but not see the important info

**Comment by ZaLiTHkA** [comment]
just updated the plugin, but it still does not work and I still can't load it's settings page.

looking through the log file I shared above again now, I found what I think is the error entry relating to the settings page not loading:

```
2024-08-22 10:21:00,771 [  17305] SEVERE - #c.i.u.c.QueueProcessor - No enum constant com.intellij.openapi.editor.EditorKind.
java.lang.IllegalArgumentException: No enum constant com.intellij.openapi.editor.EditorKind.
	at java.base/java.lang.Enum.valueOf(Enum.java:293)
	at com.intellij.openapi.editor.EditorKind.valueOf(EditorKind.java:13)
	at com.nasller.codeglance.config.CodeGlanceConfigurable.isModified(CodeGlanceConfigurable.kt:253)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:188)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedInternal(SettingsEditor.java:520)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedForItem(SettingsEditor.java:514)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModified(SettingsEditor.java:502)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.updateCurrent(SettingsEditor.java:230)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.updateIfCurrent(ConfigurableEditor.java:238)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$4.run(ConfigurableEditor.java:195)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:366)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:356)
	at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:313)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:292)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:79)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:292)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:262)
	at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:371)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.util.Alarm$Request.lambda$runSafely$1(Alarm.java:369)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:255)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:887)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:469)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1763)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1712)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:97)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:61)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:48)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:342)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:32)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$actionProcessor$1.performAction(IdeKeyEventDispatcher.kt:496)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$4$lambda$3(IdeKeyEventDispatcher.kt:845)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$4(IdeKeyEventDispatcher.kt:845)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1172)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:359)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:843)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:572)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:509)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:448)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:441)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:303)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:620)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$15(IdeEventQueue.kt:582)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:582)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2024-08-22 10:21:00,773 [  17307] SEVERE - #c.i.u.c.QueueProcessor - WebStorm 2024.2.0.1  Build #WS-242.20224.426
2024-08-22 10:21:00,773 [  17307] SEVERE - #c.i.u.c.QueueProcessor - JDK: 21.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-08-22 10:21:00,773 [  17307] SEVERE - #c.i.u.c.QueueProcessor - OS: Linux
2024-08-22 10:21:00,773 [  17307] SEVERE - #c.i.u.c.QueueProcessor - Plugin to blame: CodeGlance Pro version: 1.8.8
2024-08-22 10:21:00,773 [  17307] SEVERE - #c.i.u.c.QueueProcessor - Last Action: ShowSettings
```

can I clear the configuration for this particular plugin somehow? maybe starting again as though it was a fresh install might help?

**Comment by Nasller** [comment]
can you find CodeGlancePro.xml file？

**Comment by ZaLiTHkA** [comment]
> can you find CodeGlancePro.xml file？

yup, found it at the following path: `/.config/JetBrains/WebStorm2024.2/options/CodeGlancePro.xml`

current contents are as follows:

```xml
<application>
  <component name="CodeGlance Pro">
    <option name="editorKindsStr" value="" />
    <option name="mainWidth" value="198" />
    <option name="useEmptyMinimapStr" value="" />
  </component>
</application>
```

---

for comparison, I do alos still have remnants of WebStorm 2024.1 on my machine, and the copy of `CodeGlancePro.xml` for that version contains the following:

```xml
<application>
  <component name="CodeGlance Pro">
    <option name="hideOriginalScrollBar" value="true" />
    <option name="mainWidth" value="198" />
  </component>
</application>
```

**Comment by Nasller** [comment]
i found problem, please try this 
[CodeGlancePro-1.8.9-SNAPSHOT.zip](https://github.com/user-attachments/files/16709669/CodeGlancePro-1.8.9-SNAPSHOT.zip)

**Comment by ZaLiTHkA** [comment]
...and with that file open in VS Code, I manually removed the `editorKindStr` and `useEmptyMinimapStr` keys from my 2024.2 config file, and then I could access the plugin settings page again.

while all of this was open, I then enabled the "Hide Original ScrollBar And ErrorStripes" option again, and the file contents updated to exactly what my preious 2024.1 was. and everything still works exactly as expected.

**Comment by Nasller** [comment]
yeah, i know that, i mistake. sorry

**Comment by ZaLiTHkA** [comment]
> yeah, i know that, i mistake. sorry

no worries. :)

> i found problem, please try this [CodeGlancePro-1.8.9-SNAPSHOT.zip](https://github.com/user-attachments/files/16709669/CodeGlancePro-1.8.9-SNAPSHOT.zip)

can do, is there anything specific you need me to try using this one? or just see if it works?

**Comment by Nasller** [comment]
![image](https://github.com/user-attachments/assets/880a7017-56fe-4f3c-8b44-e62f2efdb399)
it happens in this setting is empty

**Comment by ZaLiTHkA** [comment]
> ![image](https://private-user-images.githubusercontent.com/26132153/360409505-880a7017-56fe-4f3c-8b44-e62f2efdb399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjYwOTksIm5iZiI6MTcyNDMyNTc5OSwicGF0aCI6Ii8yNjEzMjE1My8zNjA0MDk1MDUtODgwYTcwMTctNTZmZS00ZjNjLThiNDQtZTYyZjJlZmRiMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGMxNmIyODgzZTVmOGZjZjY2YWZiZjRjYTkyOTQ4MDIzNDM4ODVhYjNkYjg1ODdkOWM3NzA0Y2ExOGFmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MLfUSGN-1C2Wm2eIEW9bCPh689UzvIYR2RU11UtpMoE) it happens in this setting is empty

ah, ok... I had explictly changed that setting, so perhaps something got mixed up during settings sync then? not sure.. after clearing out those keys from the `xml` file, I see the GUI option for that is back on "Console".

let me check this with the testing build quickly, one moment...

**Comment by ZaLiTHkA** [comment]
and yes, that testing build does handle my previously problematic `CodeGlancePro.xml` file correctly:

![image](https://github.com/user-attachments/assets/61b87188-821f-4afa-a87e-f63829c84823)

**Comment by Nasller** [comment]
ok,thx

**Comment by ZaLiTHkA** [comment]
no no, thank you for the quick response.. :) glad to have the sexiest IDE sidebar minimap plugin ever made working again.

just FYI, I have reinstalled the plugin from JetBrains Marketplace for the sake of future updates. feel free to close this issue whenever you feel we're done with it. 🍻
