### ISSUE TITLE
[BUG]插件更新到1.3.6后报错:java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by WangJincheng4869** [Nasller/CodeGlancePro#24]
1. Which Glance version and IDEA version?
IntelliJ IDEA 2022.1.1 (Ultimate Edition)
2. Do you enabled reader mode option?
![image](https://user-images.githubusercontent.com/41162158/169940320-baf58e01-9dbf-4913-af2c-080d667d6867.png)

3. Could you show Glance config picture and minimap picture?

4. What steps will reproduce the issue?
启动报以下错误：

```
Worker exited due to exception

java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at java.desktop/java.awt.image.ComponentSampleModel.setSample(ComponentSampleModel.java:1123)
	at java.desktop/java.awt.image.SampleModel.setPixel(SampleModel.java:1140)
	at java.desktop/java.awt.image.WritableRaster.setPixel(WritableRaster.java:526)
	at com.nasller.codeglance.render.Minimap.setPixel(Minimap.kt:225)
	at com.nasller.codeglance.render.Minimap.renderClean(Minimap.kt:178)
	at com.nasller.codeglance.render.Minimap.renderImage(Minimap.kt:129)
	at com.nasller.codeglance.render.Minimap.update(Minimap.kt:109)
	at com.nasller.codeglance.panel.GlancePanel.computeInReadAction(GlancePanel.kt:82)
	at com.nasller.codeglance.panel.AbstractGlancePanel$updateTask$1.computeInReadAction(AbstractGlancePanel.kt:45)
	at com.intellij.openapi.progress.util.ReadTask.performInReadAction(ReadTask.java:49)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:265)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:263)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:213)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

![image](https://user-images.githubusercontent.com/41162158/169940471-6f078887-1e0a-4f68-bb17-670a0d7d175f.png)

**Comment by WangJincheng4869** [comment]
![image](https://user-images.githubusercontent.com/41162158/169941039-f5f18693-f538-45fb-aa12-d92f4e070da7.png)

**Comment by Nasller** [comment]
一直报错嘛，还是刚下报错

**Comment by WangJincheng4869** [comment]
> 一直报错嘛，还是刚下报错

并非每次都报错，是偶尔会出现，频率不高

**Comment by Nasller** [comment]
真奇怪了，我一次都没报这个

**Comment by WangJincheng4869** [comment]
> 真奇怪了，我一次都没报这个

可能是什么奇怪的条件触发的吧，先挂着吧，看其他人会不会也出现

**Comment by Nasller** [comment]
[CodeGlance Pro-1.3.6.zip](https://github.com/Nasller/CodeGlancePro/files/8759393/CodeGlance.Pro-1.3.6.zip)
试下这个

**Comment by WangJincheng4869** [comment]
> [CodeGlance Pro-1.3.6.zip](https://github.com/Nasller/CodeGlancePro/files/8759393/CodeGlance.Pro-1.3.6.zip) 试下这个
测试和几次没法发现报错，无论是这个还是市场下载的。都无法复现报错了.....

**Comment by Nasller** [comment]
> > [CodeGlance Pro-1.3.6.zip](https://github.com/Nasller/CodeGlancePro/files/8759393/CodeGlance.Pro-1.3.6.zip) 试下这个
> 
> 测试和几次没法发现报错，无论是这个还是市场下载的。都无法复现报错了.....
> 
> 

好吧，那我还是还原之前改的这个吧
