### ISSUE TITLE
[BUG] Illegal argument exception with Rider 2022.2 EAP5

### ISSUE THREAD

**Issue by warpedgeoid** [Nasller/CodeGlancePro#30]
CodeGlancePro throws an IllegalArgumentException when running on Rider 2022.2 EAP5.
```
Worker exited due to exception

java.lang.IllegalArgumentException: w and h must be > 0
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:281)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:391)
	at com.nasller.codeglance.render.Minimap.update(Minimap.kt:29)
	at com.nasller.codeglance.panel.GlancePanel.computeInReadAction(GlancePanel.kt:60)
	at com.nasller.codeglance.panel.AbstractGlancePanel$updateTask$1.computeInReadAction(AbstractGlancePanel.kt:44)
	at com.intellij.openapi.progress.util.ReadTask.performInReadAction(ReadTask.java:49)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:265)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:263)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:213)
	at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:288)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

1. Which Glance version and IDEA version?
1.28 running in Rider 2022.2 EAP5

2. Do you enabled reader mode option?
No, I don't think so...

4. Could you show Glance config picture and minimap picture?
Yes

5. What steps will reproduce the issue?
Use CodeGlancePro with Rider 2022.2 EAP5

**Comment by warpedgeoid** [comment]
Here is the configuration window:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/7670504/174453154-1d096eca-8c4d-432d-bf50-249eaf5128a5.png">

**Comment by warpedgeoid** [comment]
Here is the minimap area:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/7670504/174453182-9c12a551-8968-4e38-ad0a-6a31c9c3d7f0.png">

**Comment by Nasller** [comment]
You should update the plugin to the latest version(1.4.0). The old version of the plugin will not be adapted. And that might caused by the jdk17

**Comment by Nasller** [comment]
please check this,i have try that not produce this proble
[CodeGlance Pro-1.4.0.zip](https://github.com/Nasller/CodeGlancePro/files/8934721/CodeGlance.Pro-1.4.0.zip)
m
