### ISSUE TITLE
插件异常，idea报异常说此插件不是JetBrains产品

### ISSUE THREAD

**Issue by zem558** [Nasller/CodeGlancePro#41]
java.lang.IndexOutOfBoundsException: Wrong line: 38. Available lines count: 18
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineEnd(LineSet.java:194)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineEndOffset(DocumentImpl.java:1028)
	at com.nasller.codeglance.render.Minimap.update(Minimap.kt:91)
	at com.nasller.codeglance.panel.GlancePanel.updateImgTask(GlancePanel.kt:64)
	at com.nasller.codeglance.panel.AbstractGlancePanel.updateImage$lambda-1(AbstractGlancePanel.kt:65)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by Nasller** [comment]
是偶然的，还是必现

**Comment by Aurorxa** [comment]
![Snipaste_2022-08-10_10-01-00](https://user-images.githubusercontent.com/25677587/183794027-0f0bd9fa-088f-4aa8-911a-aaa6b8e68f27.PNG)

**Comment by Nasller** [comment]
> ![Snipaste_2022-08-10_10-01-00](https://user-images.githubusercontent.com/25677587/183794027-0f0bd9fa-088f-4aa8-911a-aaa6b8e68f27.PNG)

是偶然的，还是必现

**Comment by zem558** [comment]
> 是偶然的，还是必现

我这种情况下必然会出现，就是将文档注释转化为可解析html标签显示的时候，会报这个异常不识别插件。[](https://github.com/zem558/bug_imgs/blob/main/1.png)[](https://github.com/zem558/bug_imgs/blob/main/2.png)[](https://github.com/zem558/bug_imgs/blob/main/3.png)

**Comment by Nasller** [comment]
[CodeGlance Pro-1.4.8.zip](https://github.com/Nasller/CodeGlancePro/files/9296071/CodeGlance.Pro-1.4.8.zip)
试下这个会不会

**Comment by Aurorxa** [comment]
> > ![Snipaste_2022-08-10_10-01-00](https://user-images.githubusercontent.com/25677587/183794027-0f0bd9fa-088f-4aa8-911a-aaa6b8e68f27.PNG)
> 
> 是偶然的，还是必现

感觉出现好多次了，对了 webstorm 2022 版的

**Comment by zem558** [comment]
[1](https://github.com/zem558/bug_imgs/raw/main/1.png),[2](https://github.com/zem558/bug_imgs/raw/main/2.png),[3](https://github.com/zem558/bug_imgs/raw/main/3.png)

**Comment by zem558** [comment]
> [CodeGlance Pro-1.4.8.zip](https://github.com/Nasller/CodeGlancePro/files/9296071/CodeGlance.Pro-1.4.8.zip) 试下这个会不会

好像还是报异常，我上面发的图片评论能看到不？他们发的直接显示图片，我这还需点击，不太会。

**Comment by Nasller** [comment]
行等我试试

**Comment by zem558** [comment]
![](https://github.com/zem558/bug_imgs/raw/main/1.png)
![](https://github.com/zem558/bug_imgs/raw/main/2.png)
![](https://github.com/zem558/bug_imgs/raw/main/3.png)
哦，这样发图片评论

**Comment by Nasller** [comment]
这图片要放到哪里才能识别到

**Comment by zem558** [comment]
> 这图片要放到哪里才能识别到

图片上传到自己仓库里了,然后评论时候写![](url)，url替换为仓库图片地址，比如我图1的地址为https://github.com/zem558/bug_imgs/blob/main/1.png这个，然后将blob替换为raw，即为https://github.com/zem558/bug_imgs/raw/main/1.png，替换掉上面的url，于是就显示了。我是这样操作的。

**Comment by zem558** [comment]
> > 这图片要放到哪里才能识别到
> 
> 图片上传到自己仓库里了,然后评论时候写![](url)，url替换为仓库图片地址，比如我图1的地址为[https://github.com/zem558/bug_imgs/blob/main/1.png这个，然后将blob替换为raw，即为https://github.com/zem558/bug_imgs/raw/main/1.png，替换掉上面的url，于是就显示了。我是这样操作的。](https://github.com/zem558/bug_imgs/blob/main/1.png%E8%BF%99%E4%B8%AA%EF%BC%8C%E7%84%B6%E5%90%8E%E5%B0%86blob%E6%9B%BF%E6%8D%A2%E4%B8%BAraw%EF%BC%8C%E5%8D%B3%E4%B8%BAhttps://github.com/zem558/bug_imgs/raw/main/1.png%EF%BC%8C%E6%9B%BF%E6%8D%A2%E6%8E%89%E4%B8%8A%E9%9D%A2%E7%9A%84url%EF%BC%8C%E4%BA%8E%E6%98%AF%E5%B0%B1%E6%98%BE%E7%A4%BA%E4%BA%86%E3%80%82%E6%88%91%E6%98%AF%E8%BF%99%E6%A0%B7%E6%93%8D%E4%BD%9C%E7%9A%84%E3%80%82)
上面没显示出来   英文感叹号+英文左右中括号+英文左右大括号，里面加url

**Comment by Aurorxa** [comment]
> > 这图片要放到哪里才能识别到
> 
> 图片上传到自己仓库里了,然后评论时候写![](url)，url替换为仓库图片地址，比如我图1的地址为[https://github.com/zem558/bug_imgs/blob/main/1.png这个，然后将blob替换为raw，即为https://github.com/zem558/bug_imgs/raw/main/1.png，替换掉上面的url，于是就显示了。我是这样操作的。](https://github.com/zem558/bug_imgs/blob/main/1.png%E8%BF%99%E4%B8%AA%EF%BC%8C%E7%84%B6%E5%90%8E%E5%B0%86blob%E6%9B%BF%E6%8D%A2%E4%B8%BAraw%EF%BC%8C%E5%8D%B3%E4%B8%BAhttps://github.com/zem558/bug_imgs/raw/main/1.png%EF%BC%8C%E6%9B%BF%E6%8D%A2%E6%8E%89%E4%B8%8A%E9%9D%A2%E7%9A%84url%EF%BC%8C%E4%BA%8E%E6%98%AF%E5%B0%B1%E6%98%BE%E7%A4%BA%E4%BA%86%E3%80%82%E6%88%91%E6%98%AF%E8%BF%99%E6%A0%B7%E6%93%8D%E4%BD%9C%E7%9A%84%E3%80%82)

![Snipaste_2022-08-10_11-05-53](https://user-images.githubusercontent.com/25677587/183801446-995b7983-9c18-48eb-926c-ed74d9bac90e.PNG)

**Comment by zem558** [comment]
> > > 这图片要放到哪里才能识别到
> > 
> > 
> > 图片上传到自己仓库里了,然后评论时候写![](url)，url替换为仓库图片地址，比如我图1的地址为[https://github.com/zem558/bug_imgs/blob/main/1.png这个，然后将blob替换为raw，即为https://github.com/zem558/bug_imgs/raw/main/1.png，替换掉上面的url，于是就显示了。我是这样操作的。](https://github.com/zem558/bug_imgs/blob/main/1.png%E8%BF%99%E4%B8%AA%EF%BC%8C%E7%84%B6%E5%90%8E%E5%B0%86blob%E6%9B%BF%E6%8D%A2%E4%B8%BAraw%EF%BC%8C%E5%8D%B3%E4%B8%BAhttps://github.com/zem558/bug_imgs/raw/main/1.png%EF%BC%8C%E6%9B%BF%E6%8D%A2%E6%8E%89%E4%B8%8A%E9%9D%A2%E7%9A%84url%EF%BC%8C%E4%BA%8E%E6%98%AF%E5%B0%B1%E6%98%BE%E7%A4%BA%E4%BA%86%E3%80%82%E6%88%91%E6%98%AF%E8%BF%99%E6%A0%B7%E6%93%8D%E4%BD%9C%E7%9A%84%E3%80%82)
> 
> ![Snipaste_2022-08-10_11-05-53](https://user-images.githubusercontent.com/25677587/183801446-995b7983-9c18-48eb-926c-ed74d9bac90e.PNG)

哦，可以这样啊，快捷多了，感谢指导

**Comment by Nasller** [comment]
[CodeGlance Pro-1.4.8.zip](https://github.com/Nasller/CodeGlancePro/files/9296204/CodeGlance.Pro-1.4.8.zip)
试试这个

**Comment by zem558** [comment]
> [CodeGlance Pro-1.4.8.zip](https://github.com/Nasller/CodeGlancePro/files/9296204/CodeGlance.Pro-1.4.8.zip) 试试这个

可以，完美解决了。谢谢老大
