### ISSUE TITLE
[BUG] IOException during startup

### ISSUE THREAD

**Issue by jensritter** [Nasller/CodeGlancePro#62]
1. Which Glance version and IDEA version?
* Glance : 1.5.6
* Intellij: Build #IU-223.7571.182

3. Could you show Glance config picture and minimap picture?

![image](https://user-images.githubusercontent.com/1000745/206541612-4e619c00-8511-49a2-ac1c-f0886bd93051.png)
![image](https://user-images.githubusercontent.com/1000745/206541647-5e99bb55-4b0b-48ac-bdb8-b19cbca41399.png)

4. What steps will reproduce the issue?

An exception is thrown, when (re)starting intelliJ Ultima with more than one project.
The plugin is still working with no obvious error.

This is since the initial release of "IntelliJ IDEA 2022.3"

```
  java.io.IOException: storage is alreadyMaven\Indices\Index0\data0\versions-map.dat_i closed; path C:\Users\xpadmin\AppData\Local\JetBrains\IntelliJIdea2022.3\Maven\Indices\Index0\data0\versions-map.dat_i
	  at com.intellij.util.io.PagedFileStorage.doGetBufferWrapper(PagedFileStorage.java:457)
	  at com.intellij.util.io.PagedFileStorage.getBufferWrapper(PagedFileStorage.java:431)
	  at com.intellij.util.io.PagedFileStorage.getByteBuffer(PagedFileStorage.java:213)
	  at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.lockBuffer(IntToIntBtree.java:476)
	  at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.access$300(IntToIntBtree.java:303)
	  at com.intellij.util.io.IntToIntBtree.initAccessNodeView(IntToIntBtree.java:205)
	  at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:177)
	  at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:525)
	  at com.intellij.util.io.PersistentEnumeratorBase.lambda$doEnumerate$0(PersistentEnumeratorBase.java:273)
	  at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:634)
	  at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	  at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:263)
	  at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:587)
	  at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:549)
	  at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:169)
	  at org.jetbrains.idea.maven.indices.MavenIndex.lambda$hasVersion$10(MavenIndex.java:500)
	  at org.jetbrains.idea.maven.indices.MavenIndex.doIndexTask(MavenIndex.java:534)
	  at org.jetbrains.idea.maven.indices.MavenIndex.hasVersion(MavenIndex.java:500)
	  at org.jetbrains.idea.maven.indices.MavenIndicesManager.hasLocalVersion(MavenIndicesManager.java:164)
	  at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesVersionConverter.doIsValid(MavenArtifactCoordinatesVersionConverter.kt:80)
	  at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesConverter$ConverterStrategy.isValid(MavenArtifactCoordinatesConverter.java:201)
	  at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesConverter.fromString(MavenArtifactCoordinatesConverter.java:56)
	  at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesVersionConverter.fromString(MavenArtifactCoordinatesVersionConverter.kt:35)
	  at org.jetbrains.idea.maven.dom.converters.MavenArtifactCoordinatesVersionConverter.fromString(MavenArtifactCoordinatesVersionConverter.kt:32)
	  at com.intellij.util.xml.impl.GetInvocation.getValueInner(GetInvocation.java:96)
	  at com.intellij.util.xml.impl.GetInvocation.getOrCalcValue(GetInvocation.java:71)
	  at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:59)
	  at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:655)
	  at com.intellij.util.xml.GenericDomValue$$EnhancerByJetBrainsMainCglib$$2e754a1e.getValue(<generated>)
	  at com.intellij.util.xml.impl.GenericDomValueReference.resolve(GenericDomValueReference.java:123)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.processDependencyRecurrently(MavenDomProjectProcessorUtils.java:340)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.processDependencyRecurrently(MavenDomProjectProcessorUtils.java:350)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.processDependencyRecurrently(MavenDomProjectProcessorUtils.java:350)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.lambda$processDependenciesInDependencyManagement$8(MavenDomProjectProcessorUtils.java:370)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.processProject(MavenDomProjectProcessorUtils.java:475)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.process(MavenDomProjectProcessorUtils.java:420)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils$3.doProcessParent(MavenDomProjectProcessorUtils.java:438)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils$3.doProcessParent(MavenDomProjectProcessorUtils.java:431)
	  at org.jetbrains.idea.maven.project.MavenParentProjectFileProcessor.processRepositoryParent(MavenParentProjectFileProcessor.java:102)
	  at org.jetbrains.idea.maven.project.MavenParentProjectFileProcessor.findInLocalRepository(MavenParentProjectFileProcessor.java:82)
	  at org.jetbrains.idea.maven.project.MavenParentProjectFileProcessor.process(MavenParentProjectFileProcessor.java:68)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils$DomParentProjectFileProcessor.process(MavenDomProjectProcessorUtils.java:543)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.processParentProjectFile(MavenDomProjectProcessorUtils.java:440)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.process(MavenDomProjectProcessorUtils.java:422)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.process(MavenDomProjectProcessorUtils.java:404)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.processDependenciesInDependencyManagement(MavenDomProjectProcessorUtils.java:378)
	  at org.jetbrains.idea.maven.dom.MavenDomProjectProcessorUtils.searchManagingDependency(MavenDomProjectProcessorUtils.java:276)
	  at org.jetbrains.idea.maven.dom.annotator.MavenDomGutterAnnotator.getManagingDependency(MavenDomGutterAnnotator.java:71)
	  at org.jetbrains.idea.maven.dom.annotator.MavenDomGutterAnnotator.annotateManagedDependency(MavenDomGutterAnnotator.java:56)
	  at org.jetbrains.idea.maven.dom.annotator.MavenDomGutterAnnotator.annotate(MavenDomGutterAnnotator.java:86)
	  at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	  at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:277)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:304)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	  at com.nasller.codeglance.visitor.MyRainbowVisitor.analyze(MyRainbowVisitor.kt:16)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	  at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:603)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	  at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	  at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	  at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	  at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	  at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	  at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	  at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	  at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	  at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	  at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	  at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	  at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	  at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Nasller** [comment]
ignore this,jetbrains print this
