### ISSUE TITLE
[BUG] Exception in plugin CodeGlance Pro 1.6.9

### ISSUE THREAD

**Issue by magicprinc** [Nasller/CodeGlancePro#91]
1. Which Glance version and IDEA version?
Both are the most recent.

1.6.9

IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Licensed to me

Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    analyze.exceptions.on.the.fly=true
    documentation.show.toolbar=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.intellij.kubernetes (232.8660.158)
    com.intellij.ideolog (222.1.0.0)
    com.gafner.giv (1.0.43)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    com.paperetto.dash (3.3)
    com.nasller.CodeGlancePro (1.6.9)
    com.intellij.grazie.pro (0.3.241)
    org.jetbrains.plugins.docker.gateway (232.8660.202)
    com.intellij.ml.llm (232.9520)
    com.sourcegraph.jetbrains (3.0.8)
    org.jetbrains.plugins.hocon (2023.1.0)
    String Manipulation (9.10.0)
    com.intellij.java.rareRefactorings (232.8660.142)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    org.jetbrains.jumpToLine (0.1.13)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    com.jetbrains.packagesearch.intellij-plugin (232.8660.142)
    com.intellij.datagen (232.8660.88)
    com.intellij.microservices.debugger (232.8660.142)
    GsonFormatPlus (1.6.1)
    ink.organics.pojo2json (1.2.6)
    com.jetbrains.jax.ws (232.8660.142)
    org.avaje.ebean11.enhancer (13.20.0)
    com.bruce.intellijplugin.generatesetter (2.8.3)
    fr.jukien.intellij.plugins.pojo-generator (2.5.0)
    izhangzhihao.rainbow.brackets (2023.3.2)
    com.intellij.bigdatatools.core (232.8660.206)
    com.intellij.bigdatatools.kafka (232.8660.206)
    com.intellij.bigdatatools.binary.files (232.8660.206)
    com.intellij.bigdatatools.rfs (232.8660.206)
    com.intellij.bigdatatools.metastore.core (232.8660.206)
    com.intellij.bigdatatools.flink (232.8660.206)
    com.intellij.bigdatatools.spark (232.8660.206)
    com.intellij.bigdatatools.zeppelin (232.8660.206)
    com.intellij.bigdatatools (232.8660.206)

Kotlin: 232-1.9.0-IJ8660.185

3. Could you show Glance config picture and minimap picture?
It looks as usual.

4. What steps will reproduce the issue?
IDEA simply pops up a red circle from time to time. It started with recent CodeGlance upgrade.

java.lang.IndexOutOfBoundsException: chars sequence.length:0, start:0, end:1
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:33)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:206)
	at com.nasller.codeglance.render.FastMainMinimap.updateMinimapData(FastMainMinimap.kt:298)
	at com.nasller.codeglance.render.FastMainMinimap.submitUpdateMinimapDataTask$lambda$10(FastMainMinimap.kt:202)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:832)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:864)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:602)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:565)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:466)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:481)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Nasller** [comment]
Thanks feedback,will check code in tomorrow.

**Comment by magicprinc** [comment]
It happens on different files 🤷‍♀️

**Comment by Nasller** [comment]
[CodeGlance Pro-1.7.0-SNAPSHOT-signed.zip](https://github.com/Nasller/CodeGlancePro/files/12318052/CodeGlance.Pro-1.7.0-SNAPSHOT-signed.zip)
try this
